### PR TITLE
JavaScript group capstone

### PR DESCRIPTION
**Pull request by K0ppai**
We've worked on the following in this pull request,

1. Build these interfaces 
    - The home page.
    - The comments popup.

2. For Home page, we've implemented the following functions,
    - When the page loads, the webapp retrieves data from the selected API and shows the list of items on screen and the Involvement API to show the item likes.
    - When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
    - When the user clicks on the "Comments" button, the Comments popup appears.
    
3. For Comments popup, we've implemented the following functions,

    - When the popup loads, the webapp retrieves data from The selected API and shows details about the selected item and the Involvement API to show the item comments.
    - When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.
4.  Add counters functions in all the interfaces that show:

    - The number of items (home).
    - The number of comments (comments popup)
 5. Test the counter functions using JavaScript testing library (Jest)

### CODE REVIEW

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi Team 👋, 



Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 @K0ppai, and @SAZZAD1Q2, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

👍 You did well fixing the failing test and changing content in the footer.

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add tests for edge cases as pointed out by the previous reviewer. Think about a scenario where you do not have comments/likes or content on the page versus when a comment/like or movies are added.

test


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nahnahdev — APPROVED** [review]
## Project Status: APPROVED :green_circle: 
Hi @K0ppai and @elisha2kyakpo1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights :fire: 
- Requested tests added :heavy_check_mark: 
- All tests passing :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by K0ppai** [comment]
Thank you for the reviews.

**Pull request merged**
